#!/bin/sh
#
# $FreeBSD$
#
# PROVIDE: flowd
# REQUIRE: DAEMON
#
# Add the following lines to /etc/rc.conf to run flowd:
#
# flowd_enable (bool):           Set it to "YES" to enable flowd.
#                                Default is "NO".
# flowd_conf (file):             Local config file.
#                                Default is "/usr/local/etc/flowd.conf".
# flowd_flags (string):          Flags to pass to flowd.
#                                Default is empty.
#

. /etc/rc.subr

name="flowd"
rcvar=flowd_enable
load_rc_config ${name}

: ${flowd_enable="NO"}
: ${flowd_conf="/usr/local/etc/flowd.conf"}

required_files="${flowd_conf}"
command="/usr/local/sbin/flowd"
command_args="-f ${flowd_conf}"

run_rc_command "$1"
