#!/bin/sh

### BEGIN INIT INFO
# Provides:          rcfilesystems
# Required-Start:    $root $mountcritlocal $cleanvar
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: for services which require filesystems to be mounted before starting
# Description:       for services which require filesystems to be mounted before starting
### END INIT INFO


#
# $FreeBSD$
#

# PROVIDE: FILESYSTEMS
# REQUIRE: root mountcritlocal cleanvar

#	This is a dummy dependency, for services which require filesystems
#	to be mounted before starting.  It also serves as the default early /
#	late divider; after this point, rc.d directories are rescanned to
#	catch scripts from other filesystems than /.
