#!/bin/sh

### BEGIN INIT INFO
# Provides:          rclogin
# Required-Start:    $rcdaemon
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: ensure user services such as xdm, inetd, cron and kerberos are started after everything else
# Description:       ensure user services such as xdm, inetd, cron and kerberos are started after everything else
### END INIT INFO


#
# $FreeBSD$
#

# PROVIDE: LOGIN
# REQUIRE: DAEMON

#	This is a dummy dependency to ensure user services such as xdm,
#	inetd, cron and kerberos are started after everything else, in case
#	the administrator has increased the system security level and
#	wants to delay user logins until the system is (almost) fully
#	operational.
