#!/bin/sh

### BEGIN INIT INFO
# Provides:          rcservers
# Required-Start:    $mountcritremote $abi $ldconfig $savecore $watchdogd
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: for early-start servers relying on some basic configuration.
# Description:       for early-start servers relying on some basic configuration.
### END INIT INFO


#
# $FreeBSD$
#

# PROVIDE: SERVERS
# REQUIRE: mountcritremote abi ldconfig savecore watchdogd

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
