<?php
    echo 'OCSP_REVOKED_STATUS_NOSTATUS='.OCSP_REVOKED_STATUS_NOSTATUS;
    echo 'OCSP_REVOKED_STATUS_UNSPECIFIED='.OCSP_REVOKED_STATUS_UNSPECIFIED;
    echo 'OCSP_REVOKED_STATUS_KEYCOMPROMISE='.OCSP_REVOKED_STATUS_KEYCOMPROMISE;
    echo 'OCSP_REVOKED_STATUS_CACOMPROMISE='.OCSP_REVOKED_STATUS_CACOMPROMISE;
    echo 'OCSP_REVOKED_STATUS_AFFILIATIONCHANGED='.OCSP_REVOKED_STATUS_AFFILIATIONCHANGED;
    echo 'OCSP_REVOKED_STATUS_SUPERSEDED='.OCSP_REVOKED_STATUS_SUPERSEDED;
    echo 'OCSP_REVOKED_STATUS_CESSATIONOFOPERATION='.OCSP_REVOKED_STATUS_CESSATIONOFOPERATION;
    echo 'OCSP_REVOKED_STATUS_CERTIFICATEHOLD='.OCSP_REVOKED_STATUS_CERTIFICATEHOLD;
?>

