#!/bin/sh

exec /usr/local/sbin/openvpn --script-security 2 \
    --up /usr/local/libexec/openvpn-client.up \
    --plugin openvpn-plugin-down-root.so /usr/local/libexec/openvpn-client.down \
    --config "$@"
